#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  cache:clear)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    [[ ! -d "$DOKKU_ROOT/$2" ]] && echo "App $2 does not exist" && exit 1
    APP="$2"; IMAGE="dokku/$APP"; CACHE_DIR="$DOKKU_ROOT/$APP/cache"

    [[ ! -d $CACHE_DIR ]] && echo "App $2 does not have a cache folder" && exit 0
    docker run -v $CACHE_DIR:/cache $IMAGE /bin/sh -c "find /cache -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf"
    echo "Clearing cache for $APP... done"
    ;;

  help | apps:help)
    cat && cat<<EOF
    cache:clear <app>                               Clear the cache for an app
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
